before_install:
  - pod repo update

language: objective-c
xcode_workspace: WeiWebRTC.xcworkspace # path to your xcodeproj folder
xcode_scheme: WeiWebRTC
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
